### ISSUE TITLE
The Learn IDE

### ISSUE THREAD

**Issue by CodeByLine** [learn-co-curriculum/sinatra-cookies-readme#13]
I wonder if the Learn IDE has a bug.

Example #1:
After I passed the lab 'sinatra-nested-forms-lab-superheros-v-000', I ran "shotgun" and saw that I needed to go to 'localhost:3103'. However, I couldn't see the web pages at `localhost:3103`, no matter what I did.

As a last resort, I went to my Terminal, git cloned the lab, and ran 'shotgun'. "localhost:3103: became 'localhost:9393' and the web pages showed up.
#2

I was trying out different things in `rake console`. Someone gave me a tip on how to test params. If  If I copied the line (which is: `params = { team: { name: 'Magic } }`), it would work. But if I typed in the same phrase, I'd get an error message. (I compared my typed line w the copied line--they were identical.) This has happened on several occasions this week.

**Comment by AnnJohn** [comment]
hi @CodeByLine apologies for the lengthy delay. I'm assuming that this problem has been resolved, but if it hasn't then please file a bug report as this looks like  a product issue. 

Thanks!

**Comment by CodeByLine** [comment]
No worries--I ended up liking using the command line.
